from enum import Enum

class SubmissionStatus(Enum):
    UPLOADING = 1
    UPLOAD_COMPLETE = 2
    VALIDATING_XSD = 3
    VALIDATING_XSD_FAILED = 4
    SHREDDING_SUBMISSION = 5
    SHREDDING_SUBMISSION_COMPLETE = 6
    PROCESSING_RAW_DATA = 7
    PROCESSING_COMPLETE = 8
    RUNNING_RULE_ENGINE = 9
    RULE_ENGINE_COMPLETE = 10
    RUNNING_LLM_DEID_CHECK = 11
    RUNNING_LLM_MEDICATION_NORMALIZATION = 12
    ARCHIVING_PROCESSED_FILE = 13
    PROCESSING_FILE_COMPLETE = 14
    UPLOAD_FAILED = 15
    UPLOAD_SHREDDING_FAILED = 16
    PROCESSING_RAW_DATA_FAILED = 17
    LLM_DEID_CHECK_FAILED = 18
    LLM_MEDICATION_NORMALIZATION_FAILED = 19
    PROCESSING_FILE_FAILED = 20
    ARCHIVING_FILE_FAILED = 21
    RULE_ENGINE_FAILED = 22
